---
sidebar: sidebar 
permalink: concept-connectors.html 
keywords: 'concept, connectors, learn about connectors, service connectors, what are connectors, what is a connector, what"s a connector, days, 14 days' 
summary: 大多数情况下，您需要在云或内部网络中部署 Connector 。借助此连接器， Cloud Manager 可以管理公有云环境中的资源和流程。 
---
= 了解连接器
:hardbreaks:
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
大多数情况下，客户管理员需要在云或内部网络中部署 _Connector_ 。连接器是 Cloud Manager 日常使用的关键组件。借助此连接器， Cloud Manager 可以管理公有云环境中的资源和流程。



== 需要连接器时

要使用 Cloud Manager 中的许多功能和服务，需要使用 Connector 。



=== 服务

* 适用于 ONTAP 的 Amazon FSX 管理功能
* Amazon S3 存储分段发现
* 云备份
* 云数据感知
* 云分层
* Cloud Volumes ONTAP
* 全局文件缓存
* Kubernetes 集群
* 监控
* 内部 ONTAP 集群


以下服务需要使用连接器 * 。 not_* ：

* Active IQ 数字顾问
* 创建适用于 ONTAP 的 Amazon FSx 工作环境虽然创建工作环境不需要使用 Connector ，但需要使用它来创建和管理卷，复制数据以及将适用于 ONTAP 的 FSx 与 Data sense 和 Cloud Sync 等 NetApp 云服务集成。
* Azure NetApp Files
+
虽然设置和管理 Azure NetApp Files 不需要连接器，但如果要使用云数据感知扫描 Azure NetApp Files 数据，则需要连接器。

* 适用于 Google Cloud 的 Cloud Volumes Service
* Cloud Sync




=== 数字电子钱包

在几乎所有情况下，您都可以在没有连接器的情况下向数字电子钱包添加许可证。

只有在使用 Cloud Volumes ONTAP _node-based _ 许可证时，才需要使用 Connector 向数字电子钱包添加许可证。在这种情况下，需要使用连接器，因为数据是从 Cloud Volumes ONTAP 系统上安装的许可证中获取的。



== 支持的位置

以下位置支持连接器：

* Amazon Web Services
* Microsoft Azure
* Google Cloud
* 在您的内部环境中
* 在您的内部环境中，无法访问 Internet




=== 请注意 Azure 部署

如果在 Azure 中部署连接器，则应将其部署在与所管理的 Cloud Volumes ONTAP 系统相同的 Azure 区域中，或者部署在中 https://docs.microsoft.com/en-us/azure/availability-zones/cross-region-replication-azure#azure-cross-region-replication-pairings-for-all-geographies["Azure 区域对"^] 对于 Cloud Volumes ONTAP 系统。此要求可确保在 Cloud Volumes ONTAP 与其关联存储帐户之间使用 Azure 专用链路连接。 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-enabling-private-link.html["了解 Cloud Volumes ONTAP 如何使用 Azure 专用链路"^]。



=== 有关 Google Cloud 部署的注意事项

如果要在 Google Cloud 中创建 Cloud Volumes ONTAP 系统，则必须同时在 Google Cloud 中运行 Connector 。您不能使用在 AWS ， Azure 或内部运行的 Connector 。



== 不支持共享 Linux 主机

与其他应用程序共享的 VM 不支持此连接器。虚拟机必须专用于 Connector 软件。



== 第三方代理和扩展

Connector VM 不支持第三方代理或 VM 扩展。



== 连接器应保持运行状态

连接器应始终保持运行状态。对于您启用的服务的持续运行状况和运行来说，这一点非常重要。

例如，连接器是 Cloud Volumes ONTAP PAYGO 系统运行状况和操作的关键组件。如果某个连接器已关闭，则 Cloud Volumes ONTAP PAYGO 系统将在与某个连接器失去通信超过 14 天之后关闭。



== 如何创建 Connector

在工作空间管理员创建 Cloud Volumes ONTAP 工作环境并使用上述任何其他功能之前，客户管理员需要先创建连接器。

客户管理员可以通过多种方式创建 Connector ：

* 直接从 Cloud Manager （建议）
+
** link:task-creating-connectors-aws.html["在 AWS 中创建"]
** link:task-creating-connectors-azure.html["在 Azure 中创建"]
** link:task-creating-connectors-gcp.html["在 GCP 中创建"]


* 在您自己的 Linux 主机上手动安装软件
+
** link:task-installing-linux.html["在可访问 Internet 的主机上"]
** link:task-install-connector-onprem-no-internet.html["在无法访问 Internet 的内部主机上"]


* 来自云提供商的市场
+
** link:task-launching-aws-mktp.html["AWS Marketplace"]
** link:task-launching-azure-mktp.html["Azure Marketplace"]




如果需要创建一个 Connector 来完成操作， Cloud Manager 将提示您创建一个连接器。



== 权限

创建 Connector 需要特定权限，而 Connector 实例本身也需要另一组权限。



=== 创建 Connector 的权限

从 Cloud Manager 创建 Connector 的用户需要特定权限才能在您选择的云提供商中部署此实例。Cloud Manager 将在您创建 Connector 时提醒您权限要求。

https://mysupport.netapp.com/site/info/cloud-manager-policies["查看每个云提供商的策略"^]。



=== Connector 实例的权限

Connector 需要特定的云提供商权限才能代表您执行操作。例如，部署和管理 Cloud Volumes ONTAP 。

直接从 Cloud Manager 创建 Connector 时， Cloud Manager 会使用所需权限创建 Connector 。您无需执行任何操作。

如果您自己从 AWS Marketplace ， Azure Marketplace 或通过手动安装软件来创建 Connector ，则需要确保已设置正确的权限。

https://mysupport.netapp.com/site/info/cloud-manager-policies["查看每个云提供商的策略"^]



== 每个连接器的工作环境数量

Connector 可以在 Cloud Manager 中管理多个工作环境。一个 Connector 应管理的最大工作环境数因情况而异。具体取决于工作环境的类型，卷数量，要管理的容量以及用户数量。

如果您要进行大规模部署，请与 NetApp 代表合作来估算您的环境规模。如果您在此过程中遇到任何问题，请通过产品内聊天联系我们。



== 何时使用多个连接器

在某些情况下，您可能只需要一个连接器，但可能需要两个或更多连接器。

以下是几个示例：

* 您正在使用多云环境（ AWS 和 Azure ），因此在 AWS 中有一个连接器，在 Azure 中有另一个连接器。每个都管理在这些环境中运行的 Cloud Volumes ONTAP 系统。
* 服务提供商可能会使用一个 NetApp 帐户为其客户提供服务，而使用另一个帐户为其某个业务部门提供灾难恢复。每个帐户都有单独的 Connectors 。




== 在相同的工作环境中使用多个连接器

您可以同时管理具有多个连接器的工作环境，以实现灾难恢复。如果一个连接器发生故障，您可以切换到另一个连接器以立即管理工作环境。

要设置此配置，请执行以下操作：

. link:task-managing-connectors.html["切换到另一个连接器"]
. 发现现有工作环境。
+
** https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/task-adding-systems.html["将现有 Cloud Volumes ONTAP 系统添加到 Cloud Manager"^]
** https://docs.netapp.com/us-en/cloud-manager-ontap-onprem/task-discovering-ontap.html["发现 ONTAP 集群"^]


. 设置 https://docs.netapp.com/us-en/cloud-manager-cloud-volumes-ontap/concept-storage-management.html["容量管理模式"^]
+
只能将主连接器设置为 * 自动模式 * 。如果出于灾难恢复目的而切换到另一个连接器，则可以根据需要更改容量管理模式。





== 何时在连接器之间切换

创建首个 Connector 时， Cloud Manager 会自动对您创建的每个附加工作环境使用此 Connector 。创建额外的 Connector 后，您需要在它们之间切换，以查看每个 Connector 特有的工作环境。

link:task-managing-connectors.html["了解如何在连接器之间切换"]。



== 本地用户界面

而您应从执行几乎所有任务 https://cloudmanager.netapp.com["SaaS 用户界面"^]，连接器上仍提供本地用户界面。如果您在无法访问 Internet 的环境中安装 Connector ，并且需要从 Connector 本身执行一些任务，而不是从 SaaS 界面执行这些任务，则需要使用此接口：

* link:task-configuring-proxy.html["设置代理服务器"]
* 安装修补程序（您通常与 NetApp 人员一起安装修补程序）
* 下载 AutoSupport 消息（通常在遇到问题时由 NetApp 人员指导）


link:task-managing-connectors.html#access-the-local-ui["了解如何访问本地 UI"]。



== 连接器升级

只要有最新版本， Connector 就会自动将其软件更新到最新版本 link:reference-networking-cloud-manager.html["出站 Internet 访问"] 以获取软件更新。
